[package]
name = "obeli-sk-tag-ptr"
keywords = ["tag", "pointer"]
categories = ["data-structures"]
readme = "../../README.md"
description = "Utility library that enables a pointer to be associated with a tag of type `usize`"
version = "1.0.0-obeli-sk.10"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[package.metadata.docs.rs]
all-features = true
