[package]
name = "obeli-sk-small-btree"
keywords = ["small", "map"]
categories = ["data-structures"]
readme = "../../README.md"
description = "Utility library that add SmallBTreeMap data structure"
version = "1.0.0-obeli-sk.11"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true


[lints]
workspace = true

[package.metadata.docs.rs]
all-features = true

[dependencies]
arrayvec.workspace = true
